.PHONY: all cmd1 cmd2

all: cmd1 cmd2

# Command 1 timing
cmd1:
	@echo "Running command 1..."
	@time -p  ./usingdu.sh

# Command 2 timing
cmd2:
	@echo "Running command 2..."
	@time -p  ./usingfind.sh
